### ISSUE TITLE
OS X 10.10.3 crash

### ISSUE THREAD

**Issue by phrohdoh** [sigmavirus24/sprunge.py#1]
``` bash
~/projects/python/phrohbot [master|…1] 
20:25 $ python --version
Python 2.7.9+

~/projects/python/phrohbot [master|…1] 
20:24 $ pip list | grep requests
requests (2.7.0)

~/projects/python/phrohbot [master|…1] 
20:24 $ python sprunge.py -f guts.py
Traceback (most recent call last):
  File "sprunge.py", line 3, in <module>
    import requests
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/__init__.py", line 18, in <module>
    from .retry import Retry
  File "/usr/local/Cellar/python/HEAD/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/retry.py", line 14, in <module>
    log = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'
```

**Comment by sigmavirus24** [comment]
```
(tmp-798ed5d122aaeb47)~/virtualenv/tmp-798ed5d122aaeb47 pip install sprunge.py
You are using pip version 6.0.3, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting sprunge.py
  Downloading sprunge.py-0.1.1.tar.gz
Collecting requests>=0.12.1 (from sprunge.py)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |################################| 471kB 1.1MB/s
Installing collected packages: requests, sprunge.py

  Running setup.py install for sprunge.py
    changing mode of build/scripts-2.7/sprunge.py from 644 to 755
    changing mode of /Users/ian7708/virtualenv/tmp-798ed5d122aaeb47/bin/sprunge.py to 755
Successfully installed requests-2.7.0 sprunge.py-0.1.1
(tmp-798ed5d122aaeb47)~/virtualenv/tmp-798ed5d122aaeb47 python --version
Python 2.7.9
(tmp-798ed5d122aaeb47)~/virtualenv/tmp-798ed5d122aaeb47 ls
README.tmpenv       bin/                include/            lib/                pip-selfcheck.json
(tmp-798ed5d122aaeb47)~/virtualenv/tmp-798ed5d122aaeb47 sprunge.py -f pip-selfcheck.json
http://sprunge.us/bEfB

(tmp-798ed5d122aaeb47)~/virtualenv/tmp-798ed5d122aaeb47 pip list
You are using pip version 6.0.3, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pip (6.0.3)
requests (2.7.0)
setuptools (8.2.1)
sprunge.py (0.1.1)
```

I can't reproduce. Can you reproduce this in a virtual environment?

**Comment by phrohdoh** [comment]
No this works fine in a virtualenv, but this issue is regarding a `git clone` of this repo.

**Comment by sigmavirus24** [comment]
I'm not sure I understand. Could you provide some more detail please? For example what does phrohbot have to do with anything. I assume you didn't install sprunge.py from PyPI then? You're just running the script from the clone?

**Comment by phrohdoh** [comment]
Sorry the directory in the issue post is just where I happened to be, it just had some files in it that I used to test sprunge.

Yes I just did:

``` bash
$ git clone git@github.com:sigmavirus24/sprunge.py.git
[...]
$ cd sprunge.py
[...]
$ python sprunge.py -f <file>
```

**Comment by sigmavirus24** [comment]
I still can't reproduce this. https://asciinema.org/a/19587

From any of those directories can you launch the python interpreter and do `import requests`. I suspect this is a problem with how you've installed requests.

**Comment by phrohdoh** [comment]
Well this is odd, I could `import requests` in the REPL so I plainly tried:

``` bash
~/projects/python/sprunge.py [master|✔] 
09:27 $ pip uninstall requests && pip install requests
Collecting requests
  Using cached requests-2.7.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.7.0

~/projects/python/sprunge.py [master|✔] 
09:27 $ python sprunge.py -f README.rst
http://sprunge.us/UXeN
```

So it obviously works just fine now. Thanks for your help.

**Comment by sigmavirus24** [comment]
Sorry about that @Phrohdoh. That was a weird error. Cheers!
